## Game ENV

In [1]:
import numpy as np
import random
from collections import Counter

# X = '😀' #P1 X
# O = '🤖' #P2 O
# space = '🗯'

_dim = 8
_win_point = 5
X = 1 #P1 X
O = 2 #P2 O
space = 0



def initBoard():
    
    board = np.full((_dim, _dim), space, dtype=int) #space 10x10
#     board = [
#         [0, 0, 0],
#         [0, 0, 0],
#         [0, 0, 0]
#     ]
    return board

In [5]:
def getMoves(board):
    moves = []
    for i in range(len(board)):
        for j in range(len(board[i])):
            if board[i][j] == space:
                moves.append((i, j))
    return moves

In [6]:
## check
board = initBoard()
moves = getMoves(board)
move = moves[random.randint(0, len(moves) - 1)]

In [7]:
def checkWin(board):
    # transposition to check rows, then columns
    for newBoard in [board, np.transpose(board)]:
        result = checkRows(newBoard)
        if result:
            return result
        
    # check Diagonals  
    result = checkDiagonals(board)
    if result:
        return result
    
    # check draw
    if (len(getMoves(board)) == 0):
        # It's a draw
        return 0
    else:
        # Still more moves to make
        return -1


In [8]:
## 
def checkRows(board):
    for row in board:
        for i in range(0, len(row)):
            check_list = []
            for j in range(0,_win_point):
                if i <= (len(board)-_win_point):
                    check_list.append(row[i+j])
                # end if
            # next
            
            count = Counter(check_list)
            if count[O] == _win_point:
                return O
            if count[X] == _win_point:
                return X

    return None

def checkDiagonals(board):
    # right Diagonals 
    for idx, row in enumerate(board):
        if idx <= (len(board)-_win_point):
            
            for i in range(len(row)):
                check_list = []
                for j in range(0,_win_point):
                    if i <= (len(board)-_win_point):
                        if j == 0:
                            check_list.append(row[i+j])
                        else:
                            check_list.append(board[idx+j][i+j])
                            
                count = Counter(check_list)

                if count[O] == _win_point:
                    return O
                if count[X] == _win_point:
                    return X

                
    # Left Diagonals           
    for idx, row in enumerate(board):
        if idx <= (len(board)-_win_point):
            
            for i in range(len(row)):
                check_list = []
                for j in range(0,_win_point):
                    if i >= (len(board)-_win_point-1):
                        if j == 0:
                            check_list.append(row[i+j])
                        else:
                            check_list.append(board[idx+j][i-j])
                            
#                 st.write(check_list)            
                count = Counter(check_list)

                if count[O] == _win_point:
                    return O
                if count[X] == _win_point:
                    return X

                
                
                
    return None

In [9]:
def printBoard(board):
    for i in range(len(board)):
        for j in range(len(board[i])):
            mark = space
            if board[i][j] == X:
                mark = '😀'
            elif board[i][j] == O:
                mark = '🤖'
            if (j == len(board[i]) - 1):
                print(mark)
            else:
                print(str(mark) + "|", end='')
        if (i < len(board) - 1):
            print("-----")
            
            
            


In [10]:
b = initBoard()
print(b)
print(getMoves(b))
print(checkWin(b))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7)]
-1


In [11]:
b = initBoard()
# b[0][0] = X
# b[1][1] = X
# b[2][2] = X

# b[1][2] = O
# b[2][3] = O
# b[3][4] = O

# b[0][4] = X
# b[1][3] = X
# b[2][2] = X

# b[0][0] = X
# b[0][1] = X
# b[0][2] = X

# b[4][0] = X
# b[3][0] = X
# b[2][0] = X

b[3][2] = X
b[3][3] = X
b[3][4] = X



printBoard(b)
print(checkWin(b))
# OUTPUT

0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0
-----
0|0|😀|😀|😀|0|0|0
-----
0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0
-1


In [12]:
# 1 = X, 2 = O

def simulateGame(p1=None, p2=None, rnd=0):
    history = []
    board = initBoard()
    playerToMove = X
    
    while checkWin(board) == -1:
        
        # Chose a move (random or use a player model if provided)
        move = None
        if playerToMove == X and p1 != None:
            move = bestMove(board, p1, playerToMove, rnd)
        elif playerToMove == O and p2 != None:
            move = bestMove(board, p2, playerToMove, rnd)
        else:
            moves = getMoves(board)
            move = moves[random.randint(0, len(moves) - 1)]
        
        # Make the move
        board[move[0]][move[1]] = playerToMove
        
        # Add the move to the history
        history.append((playerToMove, move))
        
        # Switch the active player
        playerToMove = X if playerToMove == O else O
        
    return history

In [13]:
history = simulateGame()
print(history)

[(1, (0, 7)), (2, (1, 7)), (1, (3, 2)), (2, (6, 7)), (1, (3, 7)), (2, (4, 1)), (1, (5, 6)), (2, (0, 2)), (1, (6, 4)), (2, (0, 3)), (1, (1, 6)), (2, (6, 5)), (1, (7, 4)), (2, (3, 4)), (1, (4, 2)), (2, (1, 4)), (1, (0, 0)), (2, (3, 5)), (1, (1, 0)), (2, (0, 1)), (1, (7, 1)), (2, (2, 2)), (1, (2, 5)), (2, (5, 4)), (1, (5, 0)), (2, (7, 5)), (1, (0, 4)), (2, (7, 0)), (1, (2, 1)), (2, (1, 2)), (1, (7, 2)), (2, (4, 7)), (1, (6, 1)), (2, (4, 6)), (1, (4, 4)), (2, (5, 5)), (1, (1, 3)), (2, (2, 4)), (1, (4, 3)), (2, (5, 7)), (1, (2, 0)), (2, (0, 5)), (1, (7, 3)), (2, (4, 5))]


In [14]:
def movesToBoard(moves):
    board = initBoard()
    for move in moves:
        player = move[0]
        coords = move[1]
        board[coords[0]][coords[1]] = player
    return board

In [15]:
board = movesToBoard(history)
printBoard(board)
print(checkWin(board))

😀|🤖|🤖|🤖|😀|🤖|0|😀
-----
😀|0|🤖|😀|🤖|0|😀|🤖
-----
😀|😀|🤖|0|🤖|😀|0|0
-----
0|0|😀|0|🤖|🤖|0|😀
-----
0|🤖|😀|😀|😀|🤖|🤖|🤖
-----
😀|0|0|0|🤖|🤖|😀|🤖
-----
0|😀|0|0|😀|🤖|0|🤖
-----
🤖|😀|😀|😀|😀|🤖|0|0
2


In [16]:
## Start simulator
from tqdm import tqdm
games = []
for _ in tqdm(range(5000)):
    games.append(simulateGame())
# games = [simulateGame() for _ in range(10000)]

 55%|███████████████████████████████████████████▎                                  | 2774/5000 [01:40<01:20, 27.66it/s]


KeyboardInterrupt: 

In [ ]:
## check status
def gameStats(games, player=X):
    stats = {"win": 0, "loss": 0, "draw": 0}
    for game in games:
        result = checkWin(movesToBoard(game))
        if result == -1:
            continue
        elif result == player:
            stats["win"] += 1
        elif result == 0:
            stats["draw"] += 1
        else:
            stats["loss"] += 1
    
    winPct = stats["win"] / len(games) * 100
    lossPct = stats["loss"] / len(games) * 100
    drawPct = stats["draw"] / len(games) * 100

    print("Results for player:", player)
    print("Wins: %d (%.1f%%)" % (stats["win"], winPct))
    print("Loss: %d (%.1f%%)" % (stats["loss"], lossPct))
    print("Draw: %d (%.1f%%)" % (stats["draw"], drawPct))

In [ ]:
gameStats(games)
print()
gameStats(games, player=O)

In [400]:
import numpy as np
#save
np.array(games).dump(open('games.npy', 'wb'))
#load
myArray = np.load("games.npy",allow_pickle=True)
myArray = myArray.tolist()

D:\Miniconda\envs\interface\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


In [412]:
# games

## DNN

In [394]:
from tensorflow import keras 
# import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.backend import reshape
from keras.utils.np_utils import to_categorical
def getModel():
    numCells = _dim*_dim
    outcomes = 3
    model = Sequential()
    model.add(Dense(200, activation='relu', input_shape=(_dim*_dim, )))
    model.add(Dropout(0.2))
    model.add(Dense(125, activation='relu'))
    model.add(Dense(75, activation='relu'))
    model.add(Dropout(0.1))
    model.add(Dense(25, activation='relu'))
    model.add(Dense(outcomes, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
    return model

In [395]:
# X = '😀' #P1 X
# O = '🤖' #P2 O
# space = '🗯' #blank space 

def gamesToWinLossData(games):
    X = []
    y = []
    for game in games:
        winner = checkWin(movesToBoard(game))
        for move in range(len(game)):
            X.append(movesToBoard(game[:(move + 1)]))
            y.append(winner)


#     y = list(map(lambda item: item.replace('😀','1'), y))
#     y = list(map(lambda item: item.replace('🤖','2'), y))
    
    
    
    


    X = np.array(X).reshape((-1, _dim*_dim))
    
#     X = np.where(X=='😀',1, X) 
#     X = np.where(X=='🤖',2, X) 
#     X = np.where(X=='🗯',0, X)
#     X = X.astype(int)
    
    y = to_categorical(y)
    
    # Return an appropriate train/test split
    trainNum = int(len(X) * 0.8)
    return (X[:trainNum], X[trainNum:], y[:trainNum], y[trainNum:])

In [396]:
import numpy as np
model = getModel()
X_train, X_test, y_train, y_test = gamesToWinLossData(games)

In [397]:
i = 2
print(X_train[i],y_train[i])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0. 1. 0.]


In [398]:
import numpy as np
model = getModel()
X_train, X_test, y_train, y_test = gamesToWinLossData(games)
history = model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100, batch_size=100)

Epoch 1/100
1813/1813 [==============================] - 4s 2ms/step - loss: 0.7555 - acc: 0.5505 - val_loss: 0.8534 - val_acc: 0.5044
Epoch 2/100
1813/1813 [==============================] - 4s 2ms/step - loss: 0.5784 - acc: 0.7025 - val_loss: 0.9991 - val_acc: 0.5002
Epoch 3/100
1813/1813 [==============================] - 3s 2ms/step - loss: 0.4734 - acc: 0.7695 - val_loss: 1.0407 - val_acc: 0.4975
Epoch 4/100
1813/1813 [==============================] - 3s 2ms/step - loss: 0.4247 - acc: 0.7968 - val_loss: 1.1544 - val_acc: 0.4918
Epoch 5/100
1813/1813 [==============================] - 3s 2ms/step - loss: 0.3929 - acc: 0.8143 - val_loss: 1.2191 - val_acc: 0.4948
Epoch 6/100
1813/1813 [==============================] - 4s 2ms/step - loss: 0.3690 - acc: 0.8275 - val_loss: 1.2183 - val_acc: 0.4986
Epoch 7/100
1813/1813 [==============================] - 4s 2ms/step - loss: 0.3567 - acc: 0.8332 - val_loss: 1.2861 - val_acc: 0.4869
Epoch 8/100
1813/1813 [==============================] 

In [413]:
def bestMove(board, model, player, rnd=0):
    scores = []
    moves = getMoves(board)
    
    # Make predictions for each possible move
    for i in range(len(moves)):
        future = np.array(board)
        future[moves[i][0]][moves[i][1]] = player
        prediction = model.predict(future.reshape((-1, _dim*_dim)))[0]
        if player == 1:
            winPrediction = prediction[1]
            lossPrediction = prediction[2]
        else:
            winPrediction = prediction[2]
            lossPrediction = prediction[1]
        drawPrediction = prediction[0]
        if winPrediction - lossPrediction > 0:
            scores.append(winPrediction - lossPrediction)
        else:
            scores.append(drawPrediction - lossPrediction)

    # Choose the best move with a random factor
    bestMoves = np.flip(np.argsort(scores))
    for i in range(len(bestMoves)):
        if random.random() * rnd < 0.5:
            return moves[bestMoves[i]]

    # Choose a move completely at random
    return moves[random.randint(0, len(moves) - 1)]

In [414]:
from tqdm import tqdm
games2 = [simulateGame(p1=model) for _ in tqdm(range(1000))]

  6%|████▊                                                                         | 62/1000 [23:55<6:12:05, 23.80s/it]

KeyboardInterrupt: 

In [ ]:
gameStats(games2)

In [ ]:
import numpy as np
##--> save
np.array(games).dump(open('games2.npy', 'wb'))
##--> load
# myArray = np.load("games.npy",allow_pickle=True)
# myArray = myArray.tolist()

## AI VS Human

In [262]:
board = initBoard()
board[5][5] = 2
printBoard(board)
print(checkWin(board))
# move = bestMove(board, model, 1)
# board[move[0]][move[1]] = 1
# printBoard(board)

0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|🤖|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-1


In [263]:
# board = initBoard()
move = bestMove(board, model, 1)
board[move[0]][move[1]] = 1
printBoard(board)
print(checkWin(board))

0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|🤖|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|😀|0|0|0


In [264]:
## HUMAN
board[5][6] = 2
printBoard(board)
print(checkWin(board))

0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|🤖|🤖|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|😀|0|0|0
-1


In [265]:
# board = initBoard()
move = bestMove(board, model, 1)
board[move[0]][move[1]] = 1
printBoard(board)
print(checkWin(board))

0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|😀|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|🤖|🤖|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|😀|0|0|0
-1


In [251]:
board[3][1] = 2
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0


In [252]:
# board = initBoard()
move = bestMove(board, model, 1)
board[move[0]][move[1]] = 1
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|😀


In [253]:
board[4][1] = 2
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|😀


In [254]:
# board = initBoard()
move = bestMove(board, model, 1)
board[move[0]][move[1]] = 1
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|😀|😀


In [255]:
board[4][2] = 2
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|🤖|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|😀|😀


In [256]:
# board = initBoard()
move = bestMove(board, model, 1)
board[move[0]][move[1]] = 1
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|🤖|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|😀|😀|😀


In [257]:
board[4][3] = 2
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|🤖|🤖|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|😀|😀|😀


In [258]:
# board = initBoard()
move = bestMove(board, model, 1)
board[move[0]][move[1]] = 1
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|🤖|🤖|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|😀|😀|😀|😀


In [259]:
# board = initBoard()
move = bestMove(board, model, 1)
board[move[0]][move[1]] = 1
printBoard(board)

😀|0|0|0|0|0|0|😀|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|0|0|0|0|0|0|0|0
-----
0|🤖|🤖|🤖|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|0|0|0|0|0
-----
0|😀|0|0|0|0|0|0|0|0
-----
0|0|0|0|0|😀|😀|😀|😀|😀


In [260]:
print(checkWin(board))

1
